[package]
name = "teleport_calc"
version = "0.1.0"
edition = "2021"
author = "Dániel Buga <bugadani@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = [ "derive" ] }
petgraph = "0.6.2"
