use std::collections::HashMap;

use petgraph::prelude::DiGraphMap;

pub fn create_database() -> DiGraphMap<&'static str, usize> {
    let teleports = [
        //
        ("Aden", "Ivory Tower", 12000),
        ("Aden", "Oren", 6900),
        ("Aden", "Hunter\'s Village", 5900),
        ("Aden", "Rune", 37000),
        ("Aden", "Goddard", 8100),
        ("Aden", "Coliseum", 2000),
        ("Aden", "Blazing Swamp", 6800),
        ("Aden", "The Forbidden Gateway", 1400),
        ("Aden", "The Front of Anghell Waterfall", 2400),
        ("Aden", "Forsaken Plains", 1900),
        ("Aden", "Giran", 13000),
        ("Aden", "Heine", 59000),
        ("Aden", "Schuttgart", 53000),
        ("Aden", "Dion", 52000),
        ("Aden", "Gludio", 56000),
        ("Aden", "Seal of Shilen", 3300),
        ("Aden", "Forest of Mirrors", 4400),
        ("Aden", "Fields of Massacre", 6500),
        ("Aden", "Ancient Battleground", 5900),
        ("Aden", "Silent Valley", 6100),
        ("Aden", "ToI", 4200),
        //
        ("Dark Elven Village", "Gludio", 10000),
        (
            "Dark Elven Village",
            "Southern part of dark elven forest",
            1100,
        ),
        ("Dark Elven Village", "Dark Forest", 890),
        ("Dark Elven Village", "Spider Nest", 3600),
        ("Dark Elven Village", "Swampland", 1100),
        ("Dark Elven Village", "Neutral Zone", 1700),
        ("Dark Elven Village", "Orc Village", 13000),
        ("Dark Elven Village", "Dwarven Village", 22000),
        ("Dark Elven Village", "Talking Island Village", 24000),
        //
        ("Dion", "Gludio", 3400),
        ("Dion", "Giran", 6800),
        ("Dion", "Giran Harbor", 6500),
        ("Dion", "Heine", 12000),
        ("Dion", "Partisan Hideaway", 1700),
        ("Dion", "Bee Hive", 2900),
        ("Dion", "Goddard", 71000),
        ("Dion", "Rune Castle Town", 57000),
        ("Dion", "Schuttgart", 88000),
        ("Dion", "Aden", 52000),
        ("Dion", "Oren", 33000),
        ("Dion", "Cruma Marshlands", 760),
        ("Dion", "Cruma Tower", 2300),
        ("Dion", "Dion Pasture", 1500),
        ("Dion", "Tanor Canyon", 3800),
        //
        ("Dwarven Village", "Gludio", 32000),
        ("Dwarven Village", "The Northeast Coast", 2400),
        ("Dwarven Village", "Abandoned Coal Mines", 690),
        ("Dwarven Village", "Mithril Mines", 2200),
        ("Dwarven Village", "Dark Elven Village", 22000),
        ("Dwarven Village", "Elven Village", 23000),
        ("Dwarven Village", "Talking Island Village", 46000),
        ("Dwarven Village", "Schuttgart", 4400),
        ("Dwarven Village", "Orc Village", 17000),
        ("Dwarven Village", "Central Shore", 970),
        //
        ("Elven Village", "Gludio", 9200),
        ("Elven Village", "Elven Forest", 710),
        ("Elven Village", "Neutral Zone", 740),
        ("Elven Village", "Elven Fortress", 820),
        ("Elven Village", "Neutral Zone", 1700),
        ("Elven Village", "Dwarven Village", 23000),
        ("Elven Village", "Talking Island Village", 23000),
        ("Elven Village", "Orc Village", 18000),
        //
        ("Giran", "Dion", 6800),
        ("Giran", "Oren", 9400),
        ("Giran", "Hunter\'s Village", 4100),
        ("Giran", "Hardin\'s Private Academy", 4400),
        ("Giran", "Dragon Valley", 1800),
        ("Giran", "Heine", 7600),
        ("Giran", "Giran Harbor", 5200),
        ("Giran", "Gludio", 29000),
        ("Giran", "Goddard", 63000),
        ("Giran", "Rune", 59000),
        ("Giran", "Schuttgart", 87000),
        ("Giran", "Aden", 13000),
        ("Giran", "Antharas Lair", 7000),
        ("Giran", "Devil Isle", 5700),
        ("Giran", "Brekas Stronghold", 1000),
        //
        ("Giran Harbor", "Giran", 6300),
        ("Giran Harbor", "Dion", 6500),
        ("Giran Harbor", "Heine", 8500),
        //
        ("Gludin", "Orc village", 26000),
        ("Gludin", "Dwarven village", 38000),
        ("Gludin", "Talking Island Village", 9400),
        ("Gludin", "Elven Village", 16000),
        ("Gludin", "Dark Elven Village", 16000),
        ("Gludin", "Gludio", 7300),
        ("Gludin", "Southern entrance of wastelands", 3400),
        ("Gludin", "Abandoned Camp", 1200),
        ("Gludin", "Fellmere Harvest Grounds", 1400),
        ("Gludin", "Langk Lizardman Dwelling", 1800),
        ("Gludin", "Windy Hill", 2600),
        ("Gludin", "Turek Orc", 1800),
        ("Gludin", "Windmill Hill", 550),
        ("Gludin", "Forgotten Temple", 2000),
        ("Gludin", "Red ROck Ridge", 3700),
        //
        ("Gludio", "Elven Village", 9200),
        ("Gludio", "Dark Elven Village", 10000),
        ("Gludio", "Gludin", 7300),
        ("Gludio", "Dion", 3400),
        ("Gludio", "Windawood Manor", 1400),
        ("Gludio", "Southern Pathway to the Wasteland", 2400),
        ("Gludio", "Orc Village", 23000),
        ("Gludio", "Ant Cave", 2100),
        ("Gludio", "Dwarven Village", 32000),
        ("Gludio", "Schuttgart", 85000),
        ("Gludio", "Heine", 47000),
        ("Gludio", "Aden", 56000),
        ("Gludio", "Oren Castle Town", 35000),
        ("Gludio", "Goddard Castle Town", 71000),
        ("Gludio", "Giran Castle Town", 29000),
        ("Gludio", "Rune Castle Town", 53000),
        ("Gludio", "Ruins of Agony", 790),
        ("Gludio", "Ruins of Despair", 610),
        ("Gludio", "Windmill Hill", 2600),
        //
        ("Goddard", "Aden", 8100),
        ("Goddard", "Rune Castle Village", 10000),
        ("Goddard", "Varka Silenos Stronghold", 4200),
        ("Goddard", "Ketra Orc Outpost", 1800),
        ("Goddard", "Entrance to the Forge of the Gods", 2300),
        ("Goddard", "Gludio", 71000),
        ("Goddard", "Giran", 63000),
        ("Goddard", "Dion", 71000),
        ("Goddard", "Heine", 83000),
        ("Goddard", "Schuttgart", 10000),
        ("Goddard", "Oren", 37000),
        ("Goddard", "Hot Springs", 9300),
        ("Goddard", "Wall of Argos", 2200),
        ("Goddard", "Monastery of silence", 10000),
        //
        ("Hardin\'s Private Academy", "Giran", 4400),
        ("Hardin\'s Private Academy", "Oren", 6100),
        ("Hardin\'s Private Academy", "Hunter\'s Village", 3400),
        //
        ("Heine", "Giran", 7600),
        ("Heine", "Giran Harbor", 7100),
        ("Heine", "Dion", 12000),
        ("Heine", "Field of Silence", 2500),
        ("Heine", "Field of Whispers", 2300),
        ("Heine", "Entrance to Alligator Islands", 2100),
        ("Heine", "Oren", 50000),
        ("Heine", "Aden", 59000),
        ("Heine", "Goddard", 83000),
        ("Heine", "Rune", 82000),
        ("Heine", "Schuttgart", 100000),
        ("Heine", "Gludio", 47000),
        ("Heine", "Garden of Eva", 2400),
        //
        ("Hunter\'s Village", "Giran", 9400),
        ("Hunter\'s Village", "Oren", 4100),
        ("Hunter\'s Village", "Ivory Tower", 8200),
        ("Hunter\'s Village", "Hardin\'s Private Academy", 3400),
        ("Hunter\'s Village", "Aden", 5900),
        (
            "Hunter\'s Village",
            "Northern Pathway of Enchanted Valley",
            3600,
        ),
        (
            "Hunter\'s Village",
            "Southern Pathway of Enchanted Valley",
            1300,
        ),
        (
            "Hunter\'s Village",
            "Entrance to the Forest of Mirrors",
            2000,
        ),
        ("Hunter\'s Village", "The Front of Anghel Waterfall", 4000),
        //
        ("Ivory Tower", "Oren Castle Town", 3700),
        ("Ivory Tower", "Hunter\'s Village", 6800),
        ("Ivory Tower", "Aden", 6200),
        //
        ("Orc Village", "Immortal Plateau,Northern Region", 960),
        ("Orc Village", "Immortal Plateau,Southern Region", 2000),
        ("Orc Village", "Immortal Plateau,Southeast Region", 750),
        ("Orc Village", "Frozen Waterfall", 1600),
        ("Orc Village", "Entrance to the Cave of Trials", 1500),
        ("Orc Village", "Gludio", 23000),
        ("Orc Village", "Schuttgart", 13000),
        ("Orc Village", "Dark Elven Village", 13000),
        ("Orc Village", "Dwarven Village", 17000),
        ("Orc Village", "Talking Island Village", 35000),
        ("Orc Village", "Elven Village", 18000),
        //
        ("Oren", "Giran", 9400),
        ("Oren", "Ivory Tower", 3700),
        ("Oren", "Hunter\'s Village", 4100),
        ("Oren", "Hardin\'s Private Academy", 6100),
        ("Oren", "Aden", 6900),
        ("Oren", "Plains of Lizardmen", 1900),
        ("Oren", "Sea of Spores", 2500),
        ("Oren", "Rune", 10000),
        ("Oren", "Goddard", 37000),
        ("Oren", "Heine", 50000),
        ("Oren", "Dion", 33000),
        ("Oren", "Schuttgart", 59000),
        ("Oren", "Gludio", 35000),
        ("Oren", "Skyshadow Meadow", 780),
        ("Oren", "Forest Outlaw", 5200),
        //
        ("Rune", "Goddard Castle Village", 10000),
        ("Rune", "Giran", 59000),
        ("Rune", "Aden", 37000),
        ("Rune", "Rune Castle Town Guild", 150),
        ("Rune", "Rune Castle Town Temple", 150),
        ("Rune", "Entrance to the Forest of the Dead", 1200),
        ("Rune", "Western Entrance to the Swamp of Screams", 3000),
        ("Rune", "Rune Castle Town Store", 150),
        ("Rune", "Dion", 57000),
        ("Rune", "Gludio", 53000),
        ("Rune", "Heine", 82000),
        ("Rune", "Schuttgart", 10000),
        ("Rune", "Oren", 10000),
        ("Rune", "Beast Farm", 4800),
        ("Rune", "Valley of Saints", 3800),
        ("Rune", "Monastery of Silence", 14000),
        //
        ("Schuttgart", "Rune", 10000),
        ("Schuttgart", "Goddard", 10000),
        ("Schuttgart", "Aden", 53000),
        ("Schuttgart", "Oren", 59000),
        ("Schuttgart", "Heine", 100000),
        ("Schuttgart", "Giran", 87000),
        ("Schuttgart", "Dion", 88000),
        ("Schuttgart", "Gludio", 85000),
        ("Schuttgart", "Orc Village", 13000),
        ("Schuttgart", "Dwarven Village", 4400),
        ("Schuttgart", "Nest of Evil Spirit", 3000),
        ("Schuttgart", "Wasteland of plunder", 1600),
        ("Schuttgart", "Labyrinth of winter", 3500),
        ("Schuttgart", "Graveyard of disgrace", 1900),
        ("Schuttgart", "Farbel Ruins", 2100),
        //
        ("Talking Island Village", "Gludin", 18000),
        ("Talking Island Village", "Obelisk of Victory", 470),
        ("Talking Island Village", "Western Territory", 1000),
        ("Talking Island Village", "Elven Ruins", 830),
        ("Talking Island Village", "Singing Waterfall", 770),
        ("Talking Island Village", "Obelisk of Victory", 200),
        (
            "Talking Island Village",
            "Western Territory of Talking Island (Northern Area)",
            3000,
        ),
        ("Talking Island Village", "Elven Ruins", 2500),
        ("Talking Island Village", "Singing Waterfall", 2300),
        ("Talking Island Village", "Dark Elven Village", 24000),
        ("Talking Island Village", "Dwarven Village", 46000),
        ("Talking Island Village", "Elven Village", 23000),
        ("Talking Island Village", "Orc Village", 35000),
    ];

    let mut graph = DiGraphMap::new();

    let mut nodes = HashMap::new();

    for (from, to, price) in teleports {
        let mut add_node = |node: &'static str| {
            if !nodes.contains_key(node) {
                let idx = graph.add_node(node);
                nodes.insert(node, idx);
            }
        };

        add_node(from);
        add_node(to);

        graph.add_edge(nodes[from], nodes[to], price);
    }

    graph
}
